name 'psensor'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures psensor'
long_description 'Installs/Configures psensor'
version '0.1.0'
